GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RpbmciLCJpZCI6IjY5YmY3M2I0MTI1YWQ3MmQxYTNmNGYxZiIsImlhdCI6MTc3NDE1NTEwNH0.QlWkZNEDjWJKIaNHKOYXZ-Mow1PTW6L0-tvx0No4z4U

{
  "content": "testing token",
  "important": true
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "Testing",
  "name": "Testing Name",
  "password": "testing"
}